### ISSUE TITLE
Are you hiring?

### ISSUE THREAD

**Issue by scottrobel** [chadmckenna/qualvu-app#1]
If you are hiring I would love to give this challenge a try!

**Comment by jerelmiller** [comment]
Hey @scottrobel! Qualvu/24tru was [acquired by FocusVision](https://www.prnewswire.com/news-releases/focusvision-acquires-24tru-and-qualvu-300278832.html) back in 2016. This repo is a relic left over from before the acquisition. Sorry about that!

**Comment by scottrobel** [comment]
@jerelmiller No problem thanks for the info man!
